services:
  - type: web
    name: ai-memory-system-storage
    env: docker
    plan: starter
    healthCheckPath: /health_check
    envVars:
      - key: FIREBASE_STORAGE_BUCKET
        value: jamesmemorysync.firebasestorage.app
      - key: PROJECT_ID
        value: jamesmemorysync
    includeFiles:
      - jamesmemorysync-firebase-adminsdk-fbsvc-d142d44489.json